### ISSUE TITLE
Packaging issues - ubuntu linux

### ISSUE THREAD

**Issue by mnp** [pyrocat101/moo#10]
Node/npm noob here, feel free to shoot back.

First, on my platform, apt-get install nodejs will provide "/usr/bin/nodejs"; so there is no "node" executable.  This means the #! for ./bin/moo will not work as-is.  "nodejs bin/moo flle.md" works great, as does changing the #! env argument to nodejs.

Second, there does not appear to be a moo.js, so "npm install moo.js" complains 
    npm WARN install Refusing to install moo.js as a dependency of itself

while adding sudo and -g will just hang.

thanks.

**Comment by pyrocat101** [comment]
Hi @mnp,

I have no problem installing moo on a Ubuntu 14.04 machine. Can you show me the output of your npm?
BTW, Ubuntu/Debian's package manager install node binary as `nodejs`, which break things. Here is a discussion: https://github.com/joyent/node/issues/3911. You can either symlink `nodejs` to `node`, or install `nodejs-legacy` to solve the issue.

**Comment by mnp** [comment]
Adding a symlink resolved the first issue, and plain "sudo npm install -g
moo.js" worked for the other.  I was simply unprepared for how long it
would take.  Thanks!

Okay to close.

On Fri, Jan 9, 2015 at 3:14 AM, Linjie Ding <notifications@github.com>
wrote:

> Hi @mnp <https://github.com/mnp>,
>
> I have no problem installing moo on a Ubuntu 14.04 machine. Can you show
> me the output of your npm?
> BTW, Ubuntu/Debian's package manager install node binary as nodejs, which
> break things. Here is a discussion: joyent/node#3911
> <https://github.com/joyent/node/issues/3911>. You can either symlink
> nodejs to node, or install nodejs-legacy to solve the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrocat101/moo/issues/10#issuecomment-69305160>.
>



-- 
Mitchell Perilstein <mitchell.perilstein@gmail.com>
(484) 876-1444
