### ISSUE TITLE
Wish: option to exclude formatting

### ISSUE THREAD

**Issue by markstos** [pyrocat101/moo#12]
One way I use `moo.js` is to write content in Markdown, render it in HTML, then copy/paste the result into a Google Doc. However, the formatting doesn't transfer well, and largely needs to be manually removed and re-done later in Google Docs. 

However, the basic HTML structure with no formatting generated by `pandoc` from Markdown works very well. I can use `pandoc` for those cases, but I'm already in the flow of using `moo.js` for live previewing, so it would be nice to have a no styling option in Moo.js. 

One approach might be have a link or button in the rendered HTML that toggles the styling. Another option would be an alternate `--export` option that omits the styling. 

Thanks for considering the feature!

**Comment by pyrocat101** [comment]
Hi, this feature has been implemented in latest version of `moo`. Please use `--css / --no-css` options to switch styling.

**Comment by markstos** [comment]
Thanks!

On Sat, Jan 31, 2015 at 4:56 AM, Linjie Ding <notifications@github.com>
wrote:

> Closed #12 <https://github.com/pyrocat101/moo/issues/12>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrocat101/moo/issues/12#event-227962822>.
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
