### ISSUE TITLE
Add an option to specific a custom CSS file

### ISSUE THREAD

**Issue by loggerhead** [pyrocat101/moo#13]
As the title. BTW, moo is a wonderful tool which I have looked for a long time, thanks!

**Comment by markstos** [comment]
I still think having an option for a custom CSS file would be useful.

Here's my use case:  

A proofreader has asked for a double spaced version of my chapters. So, I would like to have a separate "proofreading" stylesheet that I use sometimes.

Without an option to provide my own stylesheet, each time I want to use a different stylesheet I need to expect to HTML and then manually add the stylesheet myself.

**Comment by pyrocat101** [comment]
@marktos Would you like send a PR for this feature?
