### ISSUE TITLE
Moo doesn't work with Misaka 2

### ISSUE THREAD

**Issue by pyrocat101** [pyrocat101/moo#16]
See https://github.com/pyrocat101/moo/pull/15

**Comment by markstos** [comment]
Thanks for working in this. I've run into some problems with parsing headers declared with dashes with the current moo/Misaka combination. Somehow the headers are getting misparsed, and the top portion of my document fails to appear.  Using dashes for level-2 headings appear to be valid according to the Markdown spec:

https://daringfireball.net/projects/markdown/syntax#header
